### ISSUE TITLE
Duplicated games in installed games list

### ISSUE THREAD

**Issue by obackhoff** [davocarli/sharedeck-y#4]
Hi! First of all I want to say that this is an awesome plugin :)

I've had this plugin since its original name and I always had some of my games show twice in the games list.

I tried uninstalling it, deleting the plugin files in the homebrew folder, deleting steam web browser cache and it does not fix the issue. 

I don't know if this is a bug or the expected behavior in some cases. 

Is there a way to remove the duplicates? Thanks in advance!

Kind regards.

**Comment by davocarli** [comment]
Hey @obackhoff apologies for the delay in addressing your issue. Life has been busy on my end but I will be sure to take a look at the issue this weekend.

A few follow-up questions - do you have an example or screenshot of a duplicated game? Are the same games always duplicated or does it change?
