### ISSUE TITLE
Plugin is not available in store anymore

### ISSUE THREAD

**Issue by denysdovhan** [davocarli/sharedeck-y#6]
Hi, I tried to install this plugin and didn't find it in Decky store

**Comment by gotgenes** [comment]
This was brought up [a few months ago in the Steam Deck subreddit](https://www.reddit.com/r/SteamDeck/comments/13j6f7r/what_happened_to_decksettings_decky_plugin/). A Steam UI update made the existing one incompatible and so it was removed from the plugin registry. I've been hoping for an update, too. I loved this plugin.

**Comment by pchristod** [comment]
@davocarli I see it's back in Decky Store, Version 1.2.0 however the plugin is not working. Fails to initialize. Is the store entry on purpose, or did the recent August steam update break the plugin again?

Edit: Seems that 1.2.0 is quite an old version so I assume the store entry isn't done on purpose.

**Comment by Twanislas** [comment]
Ping, any news ?

**Comment by JoshSchreuder** [comment]
It is working fine from latest source, but you have to deploy it yourself to Deck. Looks like it just needed a bump to the frontend lib
https://github.com/davocarli/sharedeck-y/commit/8fb740174be1f07a74fa069254c1125df68ae45e

I'm not sure why @davocarli hasn't pushed this up to the plugin registry again since then. If you'd like a hand maintaining the repo I'm happy to help out (I was able to build from source, deploy and play around a little with it) otherwise if you want I am also happy to fork and maintain that

**Comment by lothar-cell** [comment]
>  otherwise if you want I am also happy to fork and maintain that

If my vote counts, here is +1:)

**Comment by smexyxey** [comment]
> It is working fine from latest source, but you have to deploy it yourself to Deck. Looks like it just needed a bump to the frontend lib [8fb7401](https://github.com/davocarli/sharedeck-y/commit/8fb740174be1f07a74fa069254c1125df68ae45e)
> 
> I'm not sure why @davocarli hasn't pushed this up to the plugin registry again since then. If you'd like a hand maintaining the repo I'm happy to help out (I was able to build from source, deploy and play around a little with it) otherwise if you want I am also happy to fork and maintain that

I also vote for this! I actually had it working on my Steamdeck 3.5 but when I was updating other plugins it broke randomly again. Very strange.

**Comment by smexyxey** [comment]
Also how do you build it ? I couldn't find any tutorials for this.

**Comment by JoshSchreuder** [comment]
> Also how do you build it ? I couldn't find any tutorials for this.

Follow the steps in https://github.com/davocarli/sharedeck-y/issues/6#issuecomment-1730838500

Building was not super hard, getting it deployed was a bit trickier (setting up SSH, SSH keys, rsync etc.)
The VS Code tasks used are in here https://github.com/davocarli/sharedeck-y/blob/main/.vscode/tasks.json

**Comment by lothar-cell** [comment]
@JoshSchreuder Would you take over the repository if the project owner doesn't bother to answer? I don't think they get notifications about this project currently/anymore.

**Comment by JoshSchreuder** [comment]
Yeah I can, I'll leave it for a week or so and see if @davocarli is around as I don't want to walk all over their hard work but I don't mind maintaining a fork. 

This code is MIT licensed so I don't think there should be any issues in that respect but of course I would rather work with the original author if possible and they are interested

**Comment by smexyxey** [comment]
> Yeah I can, I'll leave it for a week or so and see if @davocarli is around as I don't want to walk all over their hard work but I don't mind maintaining a fork.
> 
> This code is MIT licensed so I don't think there should be any issues in that respect but of course I would rather work with the original author if possible and they are interested

I don't mind beta testing a private fork if you need before-hand lol

Also, his last update was a month ago about not being able to maintain it in the discord.

**Comment by JoshSchreuder** [comment]
If you're dying to get it working again, here's a build of the main index.js file compiled off the latest `"decky-frontend-lib": "^3.22.0"`

In general I don't recommend running random compiled code from the internet on your devices but if you want to and trust me then that's up to you 😄 

[index.zip](https://github.com/davocarli/sharedeck-y/files/12710068/index.zip)

Unzip and copy this to `/home/deck/homebrew/plugins/sharedeck-y/dist` and overwrite the existing file. 
You'll likely have to restart before and after doing this as I've found the file gets locked by Decky when it's being executed.

**Comment by stuart-russell** [comment]
> Yeah I can, I'll leave it for a week or so and see if @davocarli is around as I don't want to walk all over their hard work but I don't mind maintaining a fork.
> 
> This code is MIT licensed so I don't think there should be any issues in that respect but of course I would rather work with the original author if possible and they are interested

I'm also happy to help maintain a fork if the original author abandons the project 👍

**Comment by JoshSchreuder** [comment]
I've submitted to the plugin DB, so it's up to the Decky maintainers now whether they will accept the fork.
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/453

**Comment by davocarli** [comment]
Hi all,

Original dev here -- I posted in @JoshSchreuder's request to add it back to the store with my support. I do have some new functionality that was planned for this plugin that was in mid-development when I had to step away for personal reasons. I now plan to return to this plugin very soon and restart work on that new functionality. @JoshSchreuder if you want to DM me on Discord we can discuss collaborating on some of that.

**Comment by lothar-cell** [comment]
I don't really mind who maintains the plugin, as long as it is maintained. For now it works thanks to @JoshSchreuder's [manual method](https://github.com/davocarli/sharedeck-y/issues/6#issuecomment-1732723377).

**Comment by JoshSchreuder** [comment]
Working update should be up on the plugin DB now if you auto update through Decky 😄

**Comment by pchristod** [comment]
Great, thanks for your work on it! The manual method you described worked well in the meantime.
